### ISSUE TITLE
40105 UserTicket expired

### ISSUE THREAD

**Issue by brentonwong** [sinch/php-auth-ticket#1]
Using this snippet of code previous worked fine but recently it has not worked for me.

This is what I get after using the ticket:

`SinchError {name: "SinchError", domain: 3, code: 4000, response: Object, message: "40105 UserTicket expired."…}`

The only things I've changed are the app secret and id so I'm not entirely sure whats wrong.

**Comment by aruntime** [comment]
How you resolved this issue?
