### ISSUE TITLE
Does not work with older versions of PHP

### ISSUE THREAD

**Issue by jonnyleigh** [sinch/php-auth-ticket#2]
For older versions of PHP which do not accept the $var = [] construct, use the following for generateTicket():

public function generateTicket($username, DateTime $createdAt, $expiresIn)
        {
            $identityArray = array(
                'type' => 'username',
                'endpoint' => $username
                );
                
            $userTicket = array(
                'identity' => $identityArray,
                'expiresIn'         => $expiresIn,
                'applicationKey'    => $this->applicationKey,
                'created'           => $createdAt->format('c')
                );
        
            
            $userTicketJson = preg_replace('/\s+/', '', json_encode($userTicket));
     
            $userTicketBase64 = $this->base64Encode($userTicketJson);
     
            $digest = $this->createDigest($userTicketJson);
     
            $signature = $this->base64Encode($digest);
     
            $userTicketSigned = $userTicketBase64.':'.$signature;
     
            return $userTicketSigned;
        }

**Comment by spacedsweden** [comment]
thx
